---
title: "Linear Models"
author: "RuiJun Chen"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

Fit a first linear model!
```{r}
fit = lm(price ~stars + boro, data = nyc_airbnb) #Bronx is reference here (alphabetical)
```

```{r}
fit

summary(fit)
coef(fit)
summary(fit)$coef
```

tidy the results instead!

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)

fit %>% 
  broom::glance() #gets r-squared, p-value, df, etc, statistical values; the p-value in glance correlates to f-statistic for whole model
```

## Take a look at factors...

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro), #in order of how often they occur
    room_type = fct_infreq(room_type)
  )
```

 refit the last model
 
```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb) #now reference category is Manhattan

fit %>% 
  broom::tidy()
```
 
## diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = boro, y = resid)) +  #violin plot of residuals
  geom_violin() + 
  ylim(-500, 500) #have extreme outliers, so limit to get better look

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point() + 
  ylim(-500, 500)

modelr::add_predictions(nyc_airbnb, fit) #adds predictions in new column
```

## nesting...

```{r}
fit_interaction = lm(price ~ stars * boro, data = nyc_airbnb) #* looks at interaction between stars and boro

fit_interaction %>% 
  broom::tidy()
```

```{r}
fit_interaction = lm(price ~ stars * boro + room_type * boro, data = nyc_airbnb) #many interaction variables/coefficients

fit_interaction %>% 
  broom::tidy()
```

```{r}
nyc_airbnb %>% 
  filter(boro == "Brooklyn") %>% 
  lm(price ~ stars + room_type, data = .) %>% 
  broom::tidy()
```

Let's try to map this instead

```{r}
nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)), 
    results = map(models, broom::tidy)
  ) %>% 
  select(boro, results) %>% 
  unnest(results)
```

Let's nest neighborhoods

```{r}
manhattan_nest_lm_res = 
  nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  nest(data = -neighborhood) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)), 
    results = map(models, broom::tidy)
  ) %>% 
  select(neighborhood, results) %>% 
  unnest(results)

manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

```{r}
nyc_airbnb %>% 
  filter(neighborhood == "NoHo", room_type== "Shared room")
```

